"""
ai_detector.py — Lightweight statistical AI-generated text detection.

Uses purely statistical/linguistic features to estimate whether text was
written by a human or generated by AI. No ML model required — zero overhead.

Returns a score between 0.0 (likely human) and 1.0 (likely AI).
"""

import re
import math
from collections import Counter


def analyze_text(text: str) -> dict:
    """
    Run all statistical analyses on the given text.

    Returns:
        dict with keys:
            - ai_score: float 0.0–1.0 (probability of being AI-generated)
            - burstiness: float (sentence length variance; low = more AI-like)
            - vocab_richness: float (type-token ratio; low = more AI-like)
            - avg_sentence_length: float
            - sentence_length_std: float
            - repetition_score: float (higher = more repetitive = more AI-like)
            - punctuation_diversity: float (lower = more AI-like)
            - opener_diversity: float (higher = more diverse sentence starts)
    """
    if not text or not text.strip():
        return _empty_result()

    sentences = _split_sentences(text)
    words = _get_words(text)

    if len(sentences) < 3 or len(words) < 20:
        return _empty_result()

    # --- Individual features ---
    burstiness = _calc_burstiness(sentences)
    vocab_richness = _calc_vocab_richness(words)
    repetition = _calc_repetition_score(words)
    punct_diversity = _calc_punctuation_diversity(text)
    opener_diversity = _calc_opener_diversity(sentences)
    avg_sent_len = sum(len(s.split()) for s in sentences) / len(sentences)
    sent_len_std = _std([len(s.split()) for s in sentences])

    # --- Composite AI score ---
    # Each feature contributes a sub-score between 0 and 1
    # where 1 = "more AI-like"
    scores = []

    # Burstiness: AI has low burstiness (uniform sentence lengths)
    # Human burstiness typically > 0.4, AI < 0.25
    burst_score = max(0, 1.0 - (burstiness / 0.45))
    scores.append(("burstiness", burst_score, 0.30))

    # Vocab richness: AI can have diverse vocab, so lower weight
    vocab_score = max(0, 1.0 - (vocab_richness / 0.75))
    scores.append(("vocab_richness", vocab_score, 0.05))

    # Repetition: AI repeats phrases more
    rep_score = min(1.0, repetition / 0.10)
    scores.append(("repetition", rep_score, 0.10))

    # Punctuation diversity: AI uses less varied punctuation
    punct_score = max(0, 1.0 - (punct_diversity / 0.7))
    scores.append(("punctuation", punct_score, 0.10))

    # Opener diversity: AI starts sentences similarly — strong signal
    opener_score = max(0, 1.0 - (opener_diversity / 0.75))
    scores.append(("opener", opener_score, 0.25))

    # Sentence length uniformity: AI has more consistent lengths
    uniformity_score = max(0, 1.0 - (sent_len_std / 10.0))
    scores.append(("uniformity", uniformity_score, 0.20))

    # Weighted average
    ai_score = sum(s * w for _, s, w in scores) / sum(w for _, _, w in scores)
    ai_score = max(0.0, min(1.0, ai_score))

    return {
        "ai_score": round(ai_score, 4),
        "ai_label": _score_to_label(ai_score),
        "burstiness": round(burstiness, 4),
        "vocab_richness": round(vocab_richness, 4),
        "avg_sentence_length": round(avg_sent_len, 2),
        "sentence_length_std": round(sent_len_std, 2),
        "repetition_score": round(repetition, 4),
        "punctuation_diversity": round(punct_diversity, 4),
        "opener_diversity": round(opener_diversity, 4),
    }


# ===========================================================================
# Feature Calculators
# ===========================================================================

def _calc_burstiness(sentences: list) -> float:
    """
    Burstiness = coefficient of variation of sentence lengths.
    High burstiness → more human-like (varied sentence lengths).
    Low burstiness → more AI-like (uniform sentence lengths).
    """
    lengths = [len(s.split()) for s in sentences]
    if len(lengths) < 2:
        return 0.0
    mean_len = sum(lengths) / len(lengths)
    if mean_len == 0:
        return 0.0
    std_len = _std(lengths)
    return std_len / mean_len


def _calc_vocab_richness(words: list) -> float:
    """
    Type-Token Ratio (TTR) = unique words / total words.
    Higher TTR → richer vocabulary → more human-like.
    Normalized for text length using root TTR.
    """
    if not words:
        return 0.0
    unique = len(set(words))
    total = len(words)
    # Root TTR is more stable across text lengths
    return unique / math.sqrt(total) / math.sqrt(total)


def _calc_repetition_score(words: list) -> float:
    """
    Measure trigram (3-word phrase) repetition.
    Higher score = more repeated phrases = more AI-like.
    """
    if len(words) < 4:
        return 0.0
    trigrams = [tuple(words[i:i+3]) for i in range(len(words) - 2)]
    counts = Counter(trigrams)
    repeated = sum(1 for c in counts.values() if c > 1)
    return repeated / len(trigrams) if trigrams else 0.0


def _calc_punctuation_diversity(text: str) -> float:
    """
    Measure variety of punctuation used.
    Humans use more diverse punctuation (dashes, semicolons, parentheses).
    AI tends to stick to periods and commas.
    """
    punct_types = set(re.findall(r'[^\w\s]', text))
    all_punct = re.findall(r'[^\w\s]', text)
    if not all_punct:
        return 0.0
    # Normalize: how many unique punctuation marks per total
    return len(punct_types) / max(1, math.sqrt(len(all_punct)))


def _calc_opener_diversity(sentences: list) -> float:
    """
    Measure how varied sentence beginnings are.
    AI tends to start many sentences with "The", "This", "It", etc.
    """
    if len(sentences) < 3:
        return 1.0
    openers = []
    for s in sentences:
        words = s.strip().split()
        if words:
            openers.append(words[0].lower())
    if not openers:
        return 1.0
    unique_openers = len(set(openers))
    return unique_openers / len(openers)


# ===========================================================================
# Utilities
# ===========================================================================

def _split_sentences(text: str) -> list:
    """Split text into sentences using regex."""
    # Split on period, exclamation, question mark followed by space or end
    sentences = re.split(r'(?<=[.!?])\s+', text.strip())
    # Filter out empty or very short fragments
    return [s.strip() for s in sentences if len(s.strip().split()) >= 3]


def _get_words(text: str) -> list:
    """Extract lowercase words from text."""
    return re.findall(r'\b[a-z]+\b', text.lower())


def _std(values: list) -> float:
    """Calculate standard deviation."""
    if len(values) < 2:
        return 0.0
    mean = sum(values) / len(values)
    variance = sum((x - mean) ** 2 for x in values) / (len(values) - 1)
    return math.sqrt(variance)


def _score_to_label(score: float) -> str:
    """Convert AI score to human-readable label."""
    if score >= 0.7:
        return "Likely AI-Generated"
    elif score >= 0.5:
        return "Possibly AI-Generated"
    elif score >= 0.3:
        return "Uncertain"
    else:
        return "Likely Human-Written"


def _empty_result() -> dict:
    """Return empty result for insufficient text."""
    return {
        "ai_score": 0.0,
        "ai_label": "Insufficient text",
        "burstiness": 0.0,
        "vocab_richness": 0.0,
        "avg_sentence_length": 0.0,
        "sentence_length_std": 0.0,
        "repetition_score": 0.0,
        "punctuation_diversity": 0.0,
        "opener_diversity": 0.0,
    }


# ===========================================================================
# CLI Test
# ===========================================================================
if __name__ == "__main__":
    # Quick test
    human_text = """
    I couldn't believe what happened yesterday at the grocery store. This old man — must've been 80 — started arguing with the cashier over a coupon. "It says 50 cents off!" he kept saying. 
    The line was getting longer; people were sighing. But then? The woman behind him just paid for his entire order. $47.32. He started crying. Right there in aisle 5.
    Sometimes people surprise you, you know?
    """

    ai_text = """
    The global economy has experienced significant changes in recent years. These changes have been driven by various factors including technological advancement and policy decisions. 
    The impact of these changes has been felt across different sectors. Many industries have had to adapt to the new economic landscape. 
    The future outlook remains uncertain as various challenges continue to emerge. Experts suggest that continued monitoring and adaptation will be necessary.
    """

    print("=" * 50)
    print("HUMAN TEXT ANALYSIS:")
    result = analyze_text(human_text)
    for k, v in result.items():
        print(f"  {k}: {v}")

    print("\n" + "=" * 50)
    print("AI TEXT ANALYSIS:")
    result = analyze_text(ai_text)
    for k, v in result.items():
        print(f"  {k}: {v}")
